### ISSUE TITLE
base_helper_url is invalid

### ISSUE THREAD

**Issue by amankumar7702** [justchokingaround/vidsrc-cli#4]
The base_helper_url is not working. It is not able to decode the encoded string.

**Comment by justchokingaround** [comment]
yep, eltik isn't hosting it anymore

**Comment by amankumar7702** [comment]
Is there any workaround?

**Comment by justchokingaround** [comment]
atm not that ik of, but i will probably find a solution soon enough

**Comment by amankumar7702** [comment]
Ohh thanks

**Comment by rawgimaster** [comment]
can you tell me which type of encryption are being used

**Comment by amankumar7702** [comment]
Have no idea. I tried reverse engineering but could not find how they decrypt the URL. I think there is some token that decodes it on the server side. But there is no request going to the server.

**Comment by amankumar7702** [comment]
Did you find any solution ?

**Comment by rawgimaster** [comment]
im trying to deobfuscated the javascript file because it have inside the encryption algorithm and the key

**Comment by justchokingaround** [comment]
a4c722d77c7c739adefbc02d5b7bdb9c4bfa056f
